//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MandarinLearner.Model.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MandarinLearner.Model.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3007	ling2
        ///4E00	yi1
        ///4E01	ding1
        ///4E02	kao3
        ///4E03	qi1
        ///4E04	shang4	shang3
        ///4E05	xia4
        ///4E06
        ///4E07	wan4	mo4
        ///4E08	zhang4
        ///4E09	san1
        ///4E0A	shang4	shang3
        ///4E0B	xia4
        ///4E0C	ji1
        ///4E0D	bu4
        ///4E0E	yu3	yu4
        ///4E0F	mian3
        ///4E10	gai4
        ///4E11	chou3
        ///4E12	chou3
        ///4E13	zhuan1
        ///4E14	qie3	ju1
        ///4E15	pi1
        ///4E16	shi4
        ///4E17	shi4
        ///4E18	qiu1
        ///4E19	bing3
        ///4E1A	ye4
        ///4E1B	cong2
        ///4E1C	dong1
        ///4E1D	si1
        ///4E1E	cheng2
        ///4E1F	diu1
        ///4E20	qiu1
        ///4E21	liang3
        ///4E22	diu1
        ///4E23	you3
        ///4E24	liang3
        ///4E25	yan2
        ///4E26	bing4
        ///4E27	sang1	sang4
        ///4E28	shu4
        ///4E29	jiu1
        ///4E2A	ge4
        ///4E2B	ya1
        ///4E2C	qiang2	pan2
        ///4E2D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UnicodePinyinLookup {
            get {
                return ResourceManager.GetString("UnicodePinyinLookup", resourceCulture);
            }
        }
    }
}
